### ISSUE TITLE
I can't test the project

### ISSUE THREAD

**Issue by gabriel-fsa** [bo-mathadventure/admin#2]
Hello, I really liked the project and would like to use it and maybe contribute with some features. But I'm having difficulty using the project, and I don't have much knowledge of using Traefik, and it seems to me that the README is not up to date with the code. I would like to know if there is any tip on how to initialize and test locally.

**Comment by Gurkengewuerz** [comment]
Hey thanks for the interest in this project!
Please see https://github.com/bo-mathadventure/admin/issues/1#issuecomment-1633152714
